version: '2'

services:
    shell:
      image: springxd/shell
      container_name: shell
      links:
        - container1:container1
        - container2:container2
        - admin:admin
      volumes:
        - ./xd-be-pipeline-1.0-SNAPSHOT.jar:/xd-be-pipeline-1.0-SNAPSHOT.jar
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN
    admin:
      image: springxd/admin
      container_name: admin
      volumes:
        - ./servers.yml:/opt/spring-xd-1.3.2.RELEASE/xd/config/servers.yml
        - ./module_registry_data:/var/opt/springxd/customModules/
      links:
        - zookeeper:zookeeper
        - redis:redis
        - hsqldb:hsqldb
        - rabbitmq:rabbitmq
      ports:
        - 9393:9393
      environment:
        - REDIS_PORT_6379_TCP_PORT=6379
        - REDIS_PORT_6379_TCP_ADDR=redis
        - HSQLDB_PORT_9101_TCP_ADDR=hsqldb
        - HSQLDB_PORT_9101_TCP_PORT=9101
        - ZOOKEEPER_PORT_2181_TCP_ADDR=zookeeper
        - ZOOKEEPER_PORT_2181_TCP_PORT=2181
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN
    zookeeper:
      image: springxd/zookeeper
      container_name: zookeeper
      ports:
        - 2181:2181
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN
    container1:
      image: springxd/container
      container_name: container1
      volumes:
        - ./servers.yml:/opt/spring-xd-1.3.2.RELEASE/xd/config/servers.yml
        - ./module_registry_data:/var/opt/springxd/customModules/
      links:
        - zookeeper:zookeeper
        - hsqldb:hsqldb
        - redis:redis
        - rabbitmq:rabbitmq
        - kafka:kafka
      environment:
        - REDIS_PORT_6379_TCP_PORT=6379
        - REDIS_PORT_6379_TCP_ADDR=redis
        - HSQLDB_PORT_9101_TCP_ADDR=hsqldb
        - HSQLDB_PORT_9101_TCP_PORT=9101
        - ZOOKEEPER_PORT_2181_TCP_ADDR=zookeeper
        - ZOOKEEPER_PORT_2181_TCP_PORT=2181
      ports:
        - 9001:9000
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN
    container2:
      image: springxd/container
      container_name: container2
      volumes:
        - ./servers.yml:/opt/spring-xd-1.3.2.RELEASE/xd/config/servers.yml
        - ./module_registry_data:/var/opt/springxd/customModules/
      links:
        - zookeeper:zookeeper
        - hsqldb:hsqldb
        - redis:redis
        - rabbitmq:rabbitmq
        - kafka:kafka
      environment:
        - REDIS_PORT_6379_TCP_PORT=6379
        - REDIS_PORT_6379_TCP_ADDR=redis
        - HSQLDB_PORT_9101_TCP_ADDR=hsqldb
        - HSQLDB_PORT_9101_TCP_PORT=9101
        - ZOOKEEPER_PORT_2181_TCP_ADDR=zookeeper
        - ZOOKEEPER_PORT_2181_TCP_PORT=2181
      ports:
        - 9002:9000
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN
    hsqldb:
      image: springxd/hsqldb
      container_name: hsqldb
      ports:
        - 9101:9101
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN
    redis:
      image: redis
      container_name: redis
      ports:
        - 6379:6379
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN
    gateway-api:
      image: gateway-api:latest
      container_name: gateway-api
      links:
        - rabbitmq
        - kafka-rest-proxy:kafka-rest-proxy
        - registry:registry
      ports:
        - 8100:8099
    rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - 4369:4369
        - 5671:5671
        - 5672:5672
        - 15672:15672
        - 25672:25672
      cap_add:
        - ALL
        - NET_ADMIN
        - SYS_ADMIN

    kafka:
       image: spotify/kafka:latest
       container_name: kafka
       ports:
           - 9092:9092
           - 2182:2181
       environment:
           - ADVERTISED_HOST=kafka
           - ADVERTISED_PORT=9092
    kafka-shell:
       image: kafka:latest
       container_name: kafka_shell
       links: 
           - kafka:kafka
       environment:
           - KAFKA=kafka:9092
           - ZOOKEEPER=kafka:2182
        
    kafka-avro-consumer:
        image: kafka-consumer-avro:latest
        container_name: kafka-consumer-avro
        links: 
            - kafka:kafka
            - kafka-shell:kafka-shell

    registry:
        image: confluentinc/cp-schema-registry:3.2.1
        container_name: schema-registry
        links:
            - kafka:kafka
        ports:
            - 8082:8082
        environment:
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=kafka:2181
            - SCHEMA_REGISTRY_HOST_NAME=schema-registry
            - SCHEMA_REGISTRY_LISTENERS=http://registry:8082
    kafka-rest-proxy:
        image: confluentinc/cp-kafka-rest:3.2.1
        container_name: kafka-rest-proxy 
        links:
           - kafka:kafka
           - registry:registry
        ports:
           - 8083:8083
        environment:
           - KAFKA_REST_ZOOKEEPER_CONNECT=kafka:2181
           - KAFKA_REST_LISTENERS=http://kafka-rest-proxy:8083
           - KAFKA_REST_SCHEMA_REGISTRY_URL=http://registry:8082
           - KAFKA_REST_HOST_NAME=kafka-rest-proxy

    java-dispatcher:
        image: java-dispatcher:latest
        container_name: java-dispatcher
        links:
           - rabbitmq:rabbitmq
           - kafka-rest-proxy:kafka-rest-proxy
